### ISSUE TITLE
[Introdução] Par ou ímpar

### ISSUE THREAD

**Issue by Teethew** [barbisliboni/leet-code#1]
## Descrição

Escreva um programa que recebe um número inteiro `n`, e retorna `par` se o mesmo for par e `impar` se o número for ímpar.

Você pode inputar os valores via linha de comando e escrever as respostas no console/terminal, ou pode extrair a lógica para uma função, e inputar os valores como **argumento** dessa função e verificar as respostas como **retorno** da função.

## Casos de teste

| n | Retorno esperado |
|---|---------------------|
| 2 | `par` |
| 3 | `impar` |
| 2564585431 | `impar` |
| 212312452542312 | `par` |

**Comment by barbisliboni** [comment]
[EvenOrOdd.java](https://github.com/barbisliboni/leet-code/blob/master/src/main/java/EvenOrOdd.java)

![image](https://github.com/barbisliboni/leet-code/assets/69375387/5d6c90c4-ad9d-4d32-a6d9-1aa38692dd9e)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/45cd9ee8-c42a-4f74-97f4-68e07746d019)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/72f7fc1e-1113-4c1d-b997-ec3b63d3adeb)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/f1272dcc-6a08-4220-91e3-6e4c3b03e184)
