### ISSUE TITLE
[Iniciante] É primo ou nem?

### ISSUE THREAD

**Issue by Teethew** [barbisliboni/leet-code#2]
## Descrição

**Definição**: Um número primo é um número **inteiro positivo** maior do que 1, que possui somente **dois** divisores, ou seja, é divisível apenas por 1 e por **ele mesmo**

Escreva um programa que recebe um número inteiro `n`, e retorna `true` se o mesmo for primo e `false` se o número for primo.

Você pode inputar os valores via linha de comando e escrever as respostas no console/terminal, ou pode extrair a lógica para uma função, e inputar os valores como **argumento** dessa função e verificar as respostas como **retorno** da função.

## Casos de teste

| n | Retorno esperado |
|---|---------------------|
| 2 | `true` |
| 3 | `true` |
| 99793 | `true` |
| 332607 | `false` |
| 862067 | `true` |

**Comment by barbisliboni** [comment]
[PrimeNumberOrNot.java](https://github.com/barbisliboni/leet-code/blob/master/src/main/java/PrimeNumberOrNot.java)

![image](https://github.com/barbisliboni/leet-code/assets/69375387/82179fc3-9eb3-424e-9583-ca8e054656ed)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/fb968931-611f-4e6a-a2ca-d15b6d9346bf)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/72c95d37-9270-4228-a5e3-11e52799c64c)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/48756e7f-ff5a-493c-ac5a-a6d3d7f58edd)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/e353375e-ccdd-48fe-84bc-3bdf73ddd6e3)

**Comment by Teethew** [comment]
Não conhecia o cálculo usando a raiz quadrada do número. Muito bom
