### ISSUE TITLE
[Introdução] FizzBuzz

### ISSUE THREAD

**Issue by Teethew** [barbisliboni/leet-code#3]
## Descrição

Escreva um programa que recebe um número inteiro `n`.

Seu programa deve passar por todos os números inteiros positivos até `n` ou seja, **menores ou iguais** a `n`, e para cada número:

- Se o número for divisível por 3, deve se printar `Fizz`
- Se o número for divisível por 5, deve se printar `Buzz`
- Se o número for divisível por ambos, deve se printar `FizzBuzz`
- Se o número não se encaixar nas condições anteriores, deve se printar o próprio número.

Você pode inputar os valores via linha de comando, ou pode extrair a lógica para uma função, e inputar os valores como **argumento** dessa função.

Observação: Os valores não necessitam ser printados em sequência horizontal como nos casos de teste, podem ser printados em uma sequência vertical, sem problemas.

## Requisitos:
Deve ser utilizada a saída do console/terminal para printar o resultado.

## Casos de teste

| n | Retorno esperado |
|---|---------------------|
| 2 | `1 2`  |
| 3 | `1 2 Fizz` |
| 10 | `1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz` |
| 16 | `1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz 16` |

**Comment by barbisliboni** [comment]
[FizzBuzz.java](https://github.com/barbisliboni/leet-code/blob/master/src/main/java/ifs/FizzBuzz.java)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/81d94e0f-8a60-4031-baf8-06c10a500ba8)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/69de51bc-2498-4339-876b-cabb89611a05)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/c9706923-25db-4fa5-bd08-9cb5142a2932)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/4f942835-0af5-4d64-bf0f-7adbd3ad9c1d)
