### ISSUE TITLE
[Iniciante] Fatorial

### ISSUE THREAD

**Issue by Teethew** [barbisliboni/leet-code#4]
## Descrição

**Definição**: O fatorial de um número **inteiro positivo** n, é igual a multiplicação `n * (n - 1) * ... * 1`. 
Exemplos:

Fatorial de 3: 
`3 * 2 * 1 = 6`

Fatorial de 4:
`4 * 3 * 2 * 1 = 24`

Escreva um programa que recebe um número inteiro positivo `n`, e retorna o fatorial do mesmo.

Você pode inputar os valores via linha de comando e escrever as respostas no console/terminal, ou pode extrair a lógica para uma função, e inputar os valores como **argumento** dessa função e verificar as respostas como **retorno** da função.

## Casos de teste

| n | Retorno esperado |
|---|---------------------|
| 1 | 1 |
| 3 | 6 |
| 4 | 24 |
| 10 | 3628800 |
| 12 | 479001600 |

**Comment by barbisliboni** [comment]
[Factorial.java](https://github.com/barbisliboni/leet-code/blob/master/src/main/java/fors/Factorial.java)

![image](https://github.com/barbisliboni/leet-code/assets/69375387/cc83c0c9-4ed1-4c09-b5d7-1aa576b58406)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/ab92b816-217a-4e7e-87a4-287704071afa)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/c3c3f905-d196-4f9f-ae8b-53070a4552d3)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/943b64c7-14ce-48ac-b22d-0c866e712ff0)
![image](https://github.com/barbisliboni/leet-code/assets/69375387/c18534f0-90a4-4c17-9b2b-8c2b758a4b95)
